name=input("what is you're name")
print(name)
age=input("what is you're age")
print(age)
color=input("what is your favourite color")
print(color)
print("you're name is"+name)
print("you're age is"+age)
print("you're favourite color is"+color)
